[env:xiao-c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
board_build.partitions = partitions_tag.csv
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit SHT31 Library@^2.2.2

lib_ldf_mode = deep+

build_flags =
    -I../shared
    -DCORE_DEBUG_LEVEL=3
