[env:esp32dev]
platform = espressif32@^6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = no_ota.csv

lib_deps =
    adafruit/Adafruit SHT31 Library@^2.2.2
    bogde/HX711@^0.7.5
    h2zero/NimBLE-Arduino@^1.4.0

lib_ldf_mode = deep+

build_flags =
    -I../shared
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUHAL_LOG_DEFAULT_LEVEL=3
    -DCONFIG_PM_ENABLE
    -DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL
    -DCONFIG_BT_NIMBLE_ROLE_BROADCASTER
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL=0
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER=0
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
