[env:esp32s3]
platform = espressif32@^6.5.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 8MB
board_build.partitions = partitions_ota.csv
board_build.filesystem = littlefs
monitor_speed = 115200

lib_deps =
    bogde/HX711@^0.7.5
    h2zero/NimBLE-Arduino@^1.4.0

lib_ldf_mode = deep+

build_flags =
    -I../shared
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_PM_ENABLE
    -DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL
    -DCONFIG_BT_NIMBLE_ROLE_BROADCASTER
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL=0
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
