[platformio]
default_envs = xiao-c6-sht31

[env:esp32-base]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
framework = arduino
board_build.partitions = partitions_tag.csv
monitor_speed = 115200
lib_ldf_mode = deep+

[env:xiao-c6-sht31]
extends = esp32-base
board = esp32-c6-devkitm-1
lib_deps =
    adafruit/Adafruit SHT31 Library@^2.2.2
    knolleary/PubSubClient@^2.8
build_flags =
    -I../shared
    -DCORE_DEBUG_LEVEL=3
    -DSENSOR_SHT31
build_src_filter =
    +<*>
    -<sensor_ds18b20.cpp>

[env:xiao-c6-ds18b20]
extends = esp32-base
board = esp32-c6-devkitm-1
lib_deps =
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
    knolleary/PubSubClient@^2.8
build_flags =
    -I../shared
    -DCORE_DEBUG_LEVEL=3
    -DSENSOR_DS18B20
build_src_filter =
    +<*>
    -<sensor_sht31.cpp>

[env:native]
platform = native
test_framework = unity
test_build_src = true
build_flags =
    -std=gnu++17
    -Iinclude
    -Isrc
build_src_filter =
    +<payload.cpp>
